### ISSUE TITLE
Config Format Vote

### ISSUE THREAD

**Issue by JerryAZR** [JerryAZR/AI_LIMIT_DataOverrideKit#1]
Please vote here which config format you prefer, or add a new entry if your preferred one isn't here.

**Comment by JerryAZR** [comment]
[JSON](https://www.json.org/json-en.html)

```json
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

**Comment by JerryAZR** [comment]
[TOML](https://toml.io/en/)

```toml


# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"


```
